language: node_js
node_js:
- 8
sudo: required
services:
- docker
before_install:
- docker pull selenium/standalone-chrome:3.9.1-actinium
before_script:
- docker run -d --net=host --shm-size=2g selenium/standalone-chrome:3.8
- export DBUS_SESSION_BUS_ADDRESS=/dev/null
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- npm install
- npm install selenium-server
- ./node_modules/.bin/selenium-standalone install
- npm run start