language: node_js
node_js:
- 8
sudo: required
services:
- docker
before_install:
- docker pull codeception/codeceptjs:latest
script:
- npm install
- npm install selenium-server
- ./node_modules/.bin/selenium-standalone install
- npm run start