
# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

jobs:      
    test:
        docker:
            - image: peternguyentr/node-java-puppeteer:latest
        steps:
            - checkout
            - run:
                name: Install libs
                command: npm install
            - run:
                name: Install selenium
                command: ./node_modules/.bin/selenium-standalone install
            - run:
                name: Run e2e tests
                command: npm run start

workflows:
  version: 2.1
  test:
    jobs:
        - test